image: zephyrprojectrtos/zephyr-build:v0.24.7

variables:
  BEAGLE_SDK: "/builds/beagleconnect/sdk"
  ZEPHYR_BASE: "$BEAGLE_SDK/zephyr"
  PROJECT: greybus
  APP: samples/subsys/greybus/net

build:
  stage: build
  before_script:
    - rm -rf $BEAGLE_SDK
    - west init -m https://git.beagleboard.org/beagleconnect/zephyr/zephyr --mr demo $BEAGLE_SDK
    - cd $BEAGLE_SDK
    - west update
    - west zephyr-export
    - pip3 install -r zephyr/scripts/requirements-base.txt
  script:
    - cd $CI_PROJECT_DIR
    - west build -d buildx/freedom/$PROJECT -b beagleconnect_freedom $APP
    - west build -d buildx/freedom/mcuboot -b beagleconnect_freedom $BEAGLE_SDK/bootloader/mcuboot/boot/zephyr
    - mkdir -p build/freedom/$PROJECT-w-boot/zephyr
    - cp buildx/freedom/mcuboot/zephyr/zephyr.bin build/freedom/$PROJECT-w-boot/zephyr/zephyr.bin
    - dd conv=notrunc bs=1 if=buildx/freedom/$PROJECT/zephyr/zephyr.signed.bin of=build/freedom/$PROJECT-w-boot/zephyr/zephyr.bin seek=131072
    - cp $ZEPHYR_BASE/boards/arm/beagle_bcf/cc2538-bsl.py build/freedom/
  artifacts:
    paths:
      - build
