image: zephyrprojectrtos/zephyr-build:v0.24.7

variables:
  PROJECT: greybus
  APP: samples/subsys/greybus/net

build:
  stage: build
  before_script:
    - west init -l .
    - west update
    - west zephyr-export
    - pip3 install -r zephyr/scripts/requirements-base.txt
  script:
    - west build -d buildx/freedom/$PROJECT -b beagleconnect_freedom $APP -- -DOVERLAY_CONFIG="overlay-802154-subg.conf"
    - mkdir -p build/freedom/$PROJECT/zephyr
    - cp buildx/freedom/$PROJECT/zephyr/zephyr.bin build/freedom/$PROJECT/zephyr/zephyr.bin
  artifacts:
    paths:
      - build
