manifest:
  self:
    path: greybus
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: beagle-sdk
      url-base: https://openbeagle.org/beagleconnect/zephyr
  projects:
    - name: zephyr
      remote: beagle-sdk
      revision: demo
      import: true
