name: Greybus Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: greybus

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: greybus
        toolchains: arm-zephyr-eabi

    - name: Build for beagleconnect_freedom
      run: |
        mkdir dist

        west build -b beagleconnect_freedom -p always greybus/samples/subsys/greybus/net -- -DEXTRA_CONF_FILE=overlay-802154-subg.conf
        mv build/zephyr/zephyr.bin dist/beagleconnect_freedom_net.bin
        xz -z dist/beagleconnect_freedom_net.bin

        west build -b beagleconnect_freedom -p always greybus/samples/subsys/greybus/print_manifest
        mv build/zephyr/zephyr.bin dist/beagleconnect_freedom_print_manifest.bin
        xz -z dist/beagleconnect_freedom_print_manifest.bin
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: greybus-beagleconnect-freedom
        path: |
          dist/*
