name: Greybus Module CI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: greybus
        submodules: true

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: greybus
        toolchains: arm-zephyr-eabi

    - name: Build for beagleconnect_freedom
      run: |
        export ZEPHYR_BASE=$(pwd)/zephyr
        export CMAKE_PREFIX_PATH="$ZEPHYR_BASE/share/zephyr-package/cmake"
        
        west build -b beagleconnect_freedom -p always greybus/samples/subsys/greybus/net -- -DEXTRA_CONF_FILE=overlay-802154-subg.conf
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: greybus-beagleconnect-freedom-firmware
        path: |
          build/zephyr/zephyr.bin
