name: Greybus Module CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Twister samples
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: greybus

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: greybus
        toolchains: arm-zephyr-eabi

    - name: Build
      run: |
        mkdir dist
        west twister -T greybus/samples
        ls -la twister-out/
        ls -la twister-out/beagleconnect_freedom_cc1352p7/
        ls -la twister-out/beagleconnect_freedom_cc1352p7/zephyr/
        ls -la twister-out/beagleconnect_freedom_cc1352p7/zephyr/greybus/
        ls -la twister-out/beagleconnect_freedom_cc1352p7/zephyr/greybus/samples/
        ls -la twister-out/beagleconnect_freedom_cc1352p7/zephyr/greybus/samples/basic/
        ls -la twister-out/beagleconnect_freedom_cc1352p7/zephyr/greybus/samples/basic/sample.greybus.basic.transport.tcpip/
        ls -la twister-out/beagleconnect_freedom_cc1352p7/zephyr/greybus/samples/basic/sample.greybus.basic.transport.tcpip/basic/
        mv twister-out/beagleconnect_freedom_cc1352p7/zephyr/greybus/samples/basic/sample.greybus.basic.transport.tcpip/basic/zephyr/zephyr.bin dist/beagleconnect_freedom_subg.bin
        xz -z dist/beagleconnect_freedom_subg.bin
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: greybus-beagleconnect-freedom
        path: |
          dist/*
